### ISSUE TITLE
Action non figée et non prise en compte sur Mach 0 par ATC

### ISSUE THREAD

**Issue by ClemGLAD** [devteamreims/4me.xman.orchestrator#1]
![img_20160607_214307](https://cloud.githubusercontent.com/assets/18627265/15876648/ead307da-2d0e-11e6-9dfd-c4d971930e75.jpg)
Situation orageuse avec évitements. Décision de ne pas réduire AEE2FL donc clic 0 à 19h39TU à l'UF alors qu'une réduction d'un point de Mach est demandée par XMAN.
Pourtant colonne de gauche, le cœur 4-ME (est-ce bien le cœur ?) indique toujours une action en cours.
De plus, la vitesse XMAN ne se fige pas et est passée deux minutes plus tard à une réduction de 3 points de Mach.
L'avion était dans le bloc R donc je suis allé prendre en photo la P30 où on voit bien que le 0 validé ne noircit pas le vol et qu'il est compté parmi les 4 actions à faire au total. Ce fonctionnement n'est souhaitable selon moi.

**Comment by kouak** [comment]
Suite de la discussion ici : https://github.com/devteamreims/4ME/issues/78

Merci d'utiliser ce bug tracker : https://github.com/devteamreims/4ME/issues pour la prochaine fois :)

**Comment by ClemGLAD** [comment]
Ok, je vais regarder plus en détails le formalisme de github pour ne pas te
donner du boulot de retape à chaque retour.

En espérant aider,
Clem

2016-06-08 11:51 GMT+02:00 Benjamin Beret <notifications@github.com>:
